# Generated by Django 2.2.6 on 2019-10-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Question`s text', max_length=1000)),
                ('answers', models.BinaryField(help_text='List of answers converted to bin')),
                ('index_of_correct', models.IntegerField(help_text='Index of correct answer')),
            ],
        ),
    ]
