# Generated by Django 2.2.6 on 2019-10-28 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PackName', help_text='Name of pack', max_length=50)),
                ('reward', models.IntegerField(default=0, help_text='Reward in Paisons')),
                ('difficulty', models.IntegerField(default=0, help_text='Difficult of pack')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='Question', help_text='Question`s text', max_length=1000)),
                ('answers_json', models.CharField(default='answers', help_text='List of answers converted to json', max_length=300)),
                ('index_of_correct', models.IntegerField(default=0, help_text='Index of correct answer')),
                ('count_of_correct', models.IntegerField(default=0, help_text='Count of correct answers')),
                ('count_of_incorrect', models.IntegerField(default=0, help_text='Count of incorrect answers')),
                ('quest_pack', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.Pack')),
            ],
        ),
    ]
