# Generated by Django 2.2.6 on 2019-10-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='color',
            field=models.CharField(default='green', max_length=30),
        ),
    ]
