# Generated by Django 2.2.6 on 2019-10-23 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191024_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pack',
            old_name='pack_name',
            new_name='name',
        ),
    ]
