# Generated by Django 2.2.6 on 2019-10-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191024_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='questions_json',
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default='Question', help_text='Question`s text', max_length=1000),
        ),
    ]
