# Generated by Django 2.2.6 on 2019-10-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191024_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='difficulty',
            field=models.IntegerField(default=0, help_text='Difficult of pack'),
        ),
    ]
