# Generated by Django 2.2.6 on 2019-10-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='completed_packs',
        ),
    ]
