# Generated by Django 2.2.6 on 2019-10-29 16:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedpack',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 16, 56, 50, 995835, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='failedpack',
            name='pack',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.Pack'),
        ),
    ]
