# Generated by Django 2.2.6 on 2019-10-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_pack_difficulty'),
        ('authsys', '0002_remove_userprofile_completed_packs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed_packs',
            field=models.ManyToManyField(to='catalog.Pack'),
        ),
    ]
