# Generated by Django 2.2.6 on 2019-10-31 10:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0003_auto_20191031_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='reward_json',
            field=models.CharField(default='[]', help_text='json rewards', max_length=500),
        ),
        migrations.AlterField(
            model_name='failedpack',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 10, 20, 1, 940899, tzinfo=utc)),
        ),
    ]
