# Generated by Django 2.2.6 on 2019-10-28 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_pack_difficulty'),
        ('authsys', '0003_userprofile_completed_packs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100)),
                ('condition', models.TextField(default='text that describes achievement')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyAchievement',
            fields=[
                ('achievement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authsys.Achievement')),
                ('paisons', models.IntegerField(default=1000000)),
            ],
            bases=('authsys.achievement',),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='achievements',
            field=models.ManyToManyField(to='authsys.Achievement'),
        ),
        migrations.CreateModel(
            name='PacksAchievement',
            fields=[
                ('achievement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authsys.Achievement')),
                ('pack_set', models.ManyToManyField(to='catalog.Pack')),
            ],
            bases=('authsys.achievement',),
        ),
    ]
