# Generated by Django 2.2.6 on 2019-10-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_pack_difficulty'),
        ('authsys', '0004_auto_20191028_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedPack',
            fields=[
                ('pack_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Pack')),
                ('date', models.DateTimeField()),
            ],
            bases=('catalog.pack',),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='achievements',
            field=models.ManyToManyField(blank=True, to='authsys.Achievement'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='completed_packs',
            field=models.ManyToManyField(blank=True, related_name='completed_users', to='catalog.Pack'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='failed_packs',
            field=models.ManyToManyField(blank=True, related_name='failed_users', to='authsys.FailedPack'),
        ),
    ]
