# Generated by Django 2.2.6 on 2019-10-31 10:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0004_auto_20191031_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedpack',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 10, 27, 0, 355904, tzinfo=utc)),
        ),
    ]
