# Generated by Django 2.2.6 on 2019-10-28 18:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_pack_difficulty'),
        ('authsys', '0005_auto_20191028_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failedpack',
            name='pack_ptr',
        ),
        migrations.AddField(
            model_name='failedpack',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='failedpack',
            name='pack',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.Pack'),
        ),
        migrations.AlterField(
            model_name='failedpack',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 20, 1, 3, 755327)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
